const styles = {
    // --- Spacing: Padding ---
    "nano-p-0": "padding: 0;",
    "nano-p-1": "padding: 0.25rem;",
    "nano-p-2": "padding: 0.5rem;",
    "nano-p-3": "padding: 0.75rem;",
    "nano-p-4": "padding: 1rem;",
    "nano-p-5": "padding: 1.25rem;",
    "nano-p-6": "padding: 1.5rem;",
    "nano-p-8": "padding: 2rem;",
    "nano-px-2": "padding-left: 0.5rem; padding-right: 0.5rem;",
    "nano-px-3": "padding-left: 0.75rem; padding-right: 0.75rem;",
    "nano-px-4": "padding-left: 1rem; padding-right: 1rem;",
    "nano-px-6": "padding-left: 1.5rem; padding-right: 1.5rem;",
    "nano-py-1": "padding-top: 0.25rem; padding-bottom: 0.25rem;",
    "nano-py-2": "padding-top: 0.5rem; padding-bottom: 0.5rem;",
    "nano-py-3": "padding-top: 0.75rem; padding-bottom: 0.75rem;",
    "nano-py-4": "padding-top: 1rem; padding-bottom: 1rem;",
    "nano-py-8": "padding-top: 2rem; padding-bottom: 2rem;", // added
    "nano-pt-8": "padding-top: 2rem;", // added

    // --- Spacing: Margin ---
    "nano-m-0": "margin: 0;",
    "nano-m-1": "margin: 0.25rem;",
    "nano-m-2": "margin: 0.5rem;",
    "nano-m-3": "margin: 0.75rem;",
    "nano-m-4": "margin: 1rem;",
    "nano-m-auto": "margin: auto;",
    "nano-mx-auto": "margin-left: auto; margin-right: auto;",
    "nano-mb-1": "margin-bottom: 0.25rem;",
    "nano-mt-1": "margin-top: 0.25rem;",
    "nano-mt-2": "margin-top: 0.5rem;",
    "nano-mt-4": "margin-top: 1rem;",
    "nano-mt-6": "margin-top: 1.5rem;",
    "nano-mb-2": "margin-bottom: 0.5rem;",
    "nano-mb-4": "margin-bottom: 1rem;",
    "nano-mb-6": "margin-bottom: 1.5rem;",
    "nano-mb-8": "margin-bottom: 2rem;",
    "nano-mb-12": "margin-bottom: 3rem;",

    // --- Width / Max-width ---
    "nano-w-auto": "width: auto;",
    "nano-max-w-prose": "max-width: 480px;",
    "nano-max-w-page": "max-width: 760px;",

    // --- Colors: Background ---
    "nano-bg-white": "background-color: #ffffff;",
    "nano-bg-black": "background-color: #000000;",
    "nano-bg-gray-50": "background-color: #f9fafb;",
    "nano-bg-gray-100": "background-color: #f3f4f6;",
    "nano-bg-gray-200": "background-color: #e5e7eb;",
    "nano-bg-gray-700": "background-color: #374151;",
    "nano-bg-gray-800": "background-color: #1f2937;",
    "nano-bg-gray-900": "background-color: #111827;",
    "nano-bg-primary": "background-color: #3b82f6;",
    "nano-bg-danger": "background-color: #ef4444;",
    "nano-bg-success": "background-color: #22c55e;",

    // --- Colors: Text ---
    "nano-text-white": "color: #ffffff;",
    "nano-text-black": "color: #000000;",
    "nano-text-gray-200": "color: #e5e7eb;",
    "nano-text-gray-300": "color: #d1d5db;",
    "nano-text-gray-400": "color: #9ca3af;",
    "nano-text-gray-500": "color: #6b7280;",
    "nano-text-gray-700": "color: #374151;",
    "nano-text-gray-900": "color: #111827;",
    "nano-text-primary": "color: #3b82f6;",
    "nano-text-danger": "color: #ef4444;",
    "nano-text-success": "color: #22c55e;",

    // --- Typography: Font Size ---
    "nano-text-xs": "font-size: 0.75rem; line-height: 1rem;",
    "nano-text-sm": "font-size: 0.875rem; line-height: 1.25rem;",
    "nano-text-base": "font-size: 1rem; line-height: 1.5rem;",
    "nano-text-lg": "font-size: 1.125rem; line-height: 1.75rem;",
    "nano-text-xl": "font-size: 1.25rem; line-height: 1.75rem;",
    "nano-text-2xl": "font-size: 1.5rem; line-height: 2rem;",
    "nano-text-3xl": "font-size: 1.875rem; line-height: 2.25rem;",

    // --- Typography: Weight & Style ---
    "nano-font-normal": "font-weight: 400;",
    "nano-font-medium": "font-weight: 500;",
    "nano-font-semibold": "font-weight: 600;",
    "nano-font-bold": "font-weight: 700;",
    "nano-italic": "font-style: italic;",
    "nano-uppercase": "text-transform: uppercase;",
    "nano-tracking-wide": "letter-spacing: 0.05em;",
    "nano-leading-tight": "line-height: 1.1;",
    "nano-leading-relaxed": "line-height: 1.8;",
    "nano-underline": "text-decoration: underline;",
    "nano-no-underline": "text-decoration: none;",

    // --- Typography: Alignment ---
    "nano-text-left": "text-align: left;",
    "nano-text-center": "text-align: center;",
    "nano-text-right": "text-align: right;",

    // --- Borders ---
    "nano-border": "border: 1px solid #e5e7eb;",
    "nano-border-2": "border: 2px solid #e5e7eb;",
    "nano-border-dark": "border: 1px solid #374151;",
    "nano-border-gray-700": "border: 1px solid #374151;",
    "nano-border-none": "border: none;",
    "nano-border-t": "border-top: 1px solid #e5e7eb;",
    "nano-border-b": "border-bottom: 1px solid #e5e7eb;",
    "nano-border-t-gray-700": "border-top: 1px solid #374151;",

    // --- Border Radius ---
    "nano-rounded-none": "border-radius: 0;",
    "nano-rounded-sm": "border-radius: 0.125rem;",
    "nano-rounded": "border-radius: 0.25rem;",
    "nano-rounded-md": "border-radius: 0.375rem;",
    "nano-rounded-lg": "border-radius: 0.5rem;",
    "nano-rounded-xl": "border-radius: 0.75rem;",
    "nano-rounded-full": "border-radius: 9999px;",

    // --- Layout ---
    "nano-block": "display: block;",
    "nano-inline": "display: inline;",
    "nano-inline-block": "display: inline-block;",
    "nano-flex": "display: flex;",
    "nano-grid": "display: grid;",
    "nano-hidden": "display: none;",
    "nano-flex-col": "flex-direction: column;",
    "nano-flex-row": "flex-direction: row;",
    "nano-flex-wrap": "flex-wrap: wrap;",
    "nano-items-center": "align-items: center;",
    "nano-items-start": "align-items: flex-start;",
    "nano-items-end": "align-items: flex-end;",
    "nano-items-baseline": "align-items: baseline;",
    "nano-self-start": "align-self: flex-start;",
    "nano-justify-center": "justify-content: center;",
    "nano-justify-between": "justify-content: space-between;",
    "nano-justify-end": "justify-content: flex-end;",
    "nano-gap-1": "gap: 0.25rem;",
    "nano-gap-2": "gap: 0.5rem;",
    "nano-gap-3": "gap: 0.75rem;", // added
    "nano-gap-4": "gap: 1rem;",
    "nano-gap-6": "gap: 1.5rem;",
    "nano-gap-8": "gap: 2rem;",
    "nano-w-full": "width: 100%;",
    "nano-h-full": "height: 100%;",
    "nano-overflow-hidden": "overflow: hidden;",
    "nano-cursor-pointer": "cursor: pointer;",
    "nano-opacity-50": "opacity: 0.5;",
    "nano-relative": "position: relative;",
    "nano-shrink-0": "flex-shrink: 0;",
};

export default styles;
